### ISSUE TITLE
<App />'s renderChildren passing onAddClick to every component

### ISSUE THREAD

**Issue by hzhu** [hzhu/weworkhostels-v2#1]
```
 renderChildren () {
    return React.Children.map(this.props.children, function(child){
      return React.cloneElement(child, {onAddClick: this.props.onAddClick})
      }.bind(this)
    )
  }
```
We want to only pass `onAddClick` to `<PostaJob />` component.
Currently it passes it to all children components, including <About />

@itsanna

**Comment by itsanna** [comment]
I need to give onAddClick a better name. It points to bindActionCreators(addJob, dispatch), which returns all of our action creators wrapped with a dispatch method.

**Comment by hzhu** [comment]
Gotcha, that makes sense.

Still pondering if there's a better way to do this. <About /> is dumber than a dumb component. It's literally static content. I'm fine with keeping the way it is now. There isn't a performance hit since it's only a single component. Hypothetically if we had 100s of static components, then we'd need to figure out a better way to write this part.

I'll mark this as `won't fix` but if we can come up with a more elegant refactor, let's do it.
