### ISSUE TITLE
Dispatching too many actions.

### ISSUE THREAD

**Issue by itsanna** [hzhu/weworkhostels-v2#13]
`Firebase.on()` triggers `addJob` dispatch to store for each job item in Firebase. 
We need a more efficient solution for dispatching `addJob`. Need to explore Firebase API.

**Comment by hzhu** [comment]
We should investigate `Firebase.on('value', cb)` [API](https://www.firebase.com/docs/web/api/query/on.html)

**Comment by hzhu** [comment]
sadsadasd

**Comment by itsanna** [comment]
Switching eventType from 'child_added' to 'value' 

Will trigger once for the initial data items stored at the Firebase location & triggered each time data changes. It won't trigger until the entire contents has been synchronized [Firebase API](https://www.firebase.com/docs/web/api/query/on.html)

Seems like what we need...
