### ISSUE TITLE
Add CSS tooling

### ISSUE THREAD

**Issue by hzhu** [hzhu/weworkhostels-v2#5]
Add CSS tooling to pre / post process stylesheets

Considering Sass's SCSS via webpack

**Comment by hzhu** [comment]
Now considering: https://github.com/postcss/postcss

**Comment by hzhu** [comment]
Let's use webpack & post-css to build our CSS. Also let's use [sass](https://www.npmjs.com/package/node-sass).

Here's the demo: https://github.com/hzhu/post-css-demo

**Comment by hzhu** [comment]
https://github.com/hzhu/weworkhostels-v2/commit/224c3f4c9115bf0c6aa8abc9ceba7a3e555118be

**Comment by idibidiart** [comment]
Have u looked at Radium?

**Comment by hzhu** [comment]
Woah looks interesting! 

I'm gonna take it look soon as I get home. There's a Dan Abromov talk tonight :)

**Comment by idibidiart** [comment]
Funny last few hours i have been trying to feel my way into a solution to the mess of neated subscriptions in Redux and seems like a lot of other people noticed the issue. He's a nice dude.

**Comment by idibidiart** [comment]
*nested*
